// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const LOADING_USER_DATA = 'LOADING_USER_DATA';

export const SET_NEWS_DATA = 'SET_NEWS_DATA';
export const MARK_FAVORITE_NEWS = 'MARK_FAVORITE_NEWS';
export const UNMARK_FAVORITE_NEWS = 'UNMARK_FAVORITE_NEWS';
export const UNMARK_SINGLE_FAVORITE_NEWS = 'UNMARK_SINGLE_FAVORITE_NEWS';
export const INCREASE_NEWS_DATA_OFFSET = "INCREASE_NEWS_DATA_OFFSET";
export const CHECK_ALL_FAVORITE_NEWS = "CHECK_ALL_FAVORITE_NEWS";

export const LOADING_DATA = 'LOADING_DATA';

